### ISSUE TITLE
simpcraft

### ISSUE THREAD

**Issue by kittenvr** [coltonk9043/Aoba-Client#44]
could you make some hacks for simpcraft.com

**Comment by coltonk9043** [comment]
Isn't that the Mr. Beast server?! lmao

Honestly I've never played on it so I wouldn't know what hacks to make! If you have anything specific I'd be down to give it a go.

**Comment by kittenvr** [comment]
> Isn't that the Mr. Beast server?! lmao
> 
> Honestly I've never played on it so I wouldn't know what hacks to make! If you have anything specific I'd be down to give it a go.

if you add the fly pathfind try to test it for its speed limit

**Comment by kittenvr** [comment]
maybe find a way to bypass their speedlimit

**Comment by Noriskky** [comment]
PizzaV i have an Idea do it yourself. BTW you would even learn some stuff while doing it.

**Comment by cvs0** [comment]
Closed due to inactivity.

**Comment by kittenvr** [comment]
Is it still on the to do?
