### ISSUE TITLE
autobasefinder

### ISSUE THREAD

**Issue by kittenvr** [coltonk9043/Aoba-Client#46]
flys around in circle from start pos and if it didnt find base in the circle it expands it

**Comment by coltonk9043** [comment]
Not a bad idea. I think this might be better as a command though. Specify a max radius and then type a command to start/stop.

**Comment by kittenvr** [comment]
oh yeah true

**Comment by Tewxx** [comment]
I would love to see that

**Comment by cvs0** [comment]
Closed due to inactivity.
