### ISSUE TITLE
Xray does not work when Sodium is installed

### ISSUE THREAD

**Issue by Logging4J** [coltonk9043/Aoba-Client#65]
**Describe the bug**
Xray does not work with the mod Sodium installed. Instead of only rendering xray blocks it renders all blocks

**To Reproduce**
1. Run Aoba with Sodium
2. Turn on Xray

**Expected behavior**
Xray should only render xray blocks.

**Desktop**
 - OS: Arch Linux
 - Version: 6.11.1-arch1-1

**Comment by coltonk9043** [comment]
I will attempt to add compatibility for Sodium and other performance-enhancing mods. I don't expect it to be hugely difficult.

**Comment by cvs0** [comment]
Currently in progress.
