### ISSUE TITLE
Crashing on side mouse button press.

### ISSUE THREAD

**Issue by ytcyde** [coltonk9043/Aoba-Client#67]
The game crashes when pressing the side mouse buttons. Crash file included.

[crash-2024-10-17_15.26.18-client.txt](https://github.com/user-attachments/files/17413216/crash-2024-10-17_15.26.18-client.txt)

**Comment by coltonk9043** [comment]
This should be fixed in #63

**Comment by ytcyde** [comment]
ahh, guess I gotta compile the new version myself and not download from the releases page?

**Comment by coltonk9043** [comment]
Closing issue due to #63. Feel free to reopen it if you find any issues.
