### ISSUE TITLE
Option to save modules and their settings after closing the game

### ISSUE THREAD

**Issue by PirateLord77** [coltonk9043/Aoba-Client#71]
**Is your feature request related to a problem? Please describe.**
Simply have an option to save modules and their settings after closing the game so that they don't have to be enabled every time. It would be very convenient and is the standard for other cheats.

**Describe the solution you'd like**
Just make it a toggle that logs your modules and settings then uses those same logs on client bootup to turn on modules.

**Describe alternatives you've considered**
Alternatives could be a proper config system, where you can save and load multiple different logs.

Please fix devs <3, I love Aoba but this is just so so annoying.

**Comment by coltonk9043** [comment]
Loading and saving several different configs sounds like a great idea. I'll begin work on this when I get home today as I may have some free time. Expect it along with a macro system in a small update soon.

**Comment by coltonk9043** [comment]
Added persistent module toggle between game sessions in 1e1f80f. Working on saving/loading of different configs in the next couple of days.

**Comment by PirateLord77** [comment]
AYO BET LOOKING FORWARD TO IT

**Comment by coltonk9043** [comment]
Closing issue. Finished saving/loading in commit a5d992a
